In [0]:
%run "./Preparacao"

In [0]:
%sql
-- Teste Preparacao
SELECT * FROM temp_tables.products_2

In [0]:
%sql
-- 01) Liste os emails e primeiro nome dos clientes da tabela sales.customers

CREATE OR REPLACE TEMPORARY VIEW NomeEmail AS
SELECT email AS Email_Cliente, first_name AS Primeiro_Nome
FROM sales.customers
WHERE first_name LIKE "%W%"

In [0]:
%sql
SELECT Email_Cliente, Primeiro_Nome
FROM NomeEmail

In [0]:
%sql
-- 02) Liste as marcas de carro distintas que constam na tabela products

SELECT DISTINCT brand, COUNT (model) AS ProdutosPorMarca
FROM sales.products
group by brand
order by ProdutosPorMarca DESC;

In [0]:
%sql
-- 03) Liste os emails dos clientes da nossa base que moram no estado de Santa Catarina
-- ou Mato Grosso do Sul

SELECT  email,state,first_name
FROM sales.customers
WHERE (state = "SC" OR state =
"MT");

In [0]:
%sql
-- 04) Liste os emails dos clientes da nossa base que moram no estado de Santa Catarina 
-- ou Mato Grosso do Sul e que tem mais de 30 anos

SELECT state, email, year(birth_date) AS Ano_Nascimento,timestampdiff(YEAR,birth_date,NOW()) AS Idade
FROM sales.customers
WHERE (state = "SC" OR
state ="MT") AND timestampdiff(YEAR,birth_date,NOW()) >= 30
ORDER BY birth_date DESC;

In [0]:
%sql
-- 05) (Exemplo 1) Ordenação de valores numéricos
-- Liste produtos da tabela products na ordem crescente com base no preço

SELECT model AS Modelo, price AS Valor
FROM sales.products
ORDER BY model, price;

In [0]:
%sql
-- 06) Liste os 10 produtos mais caros da tabela products

CREATE OR REPLACE TEMPORARY VIEW Top_10_mostExpensive AS
SELECT brand, model AS Modelo, price AS Valor
FROM sales.products
ORDER BY Valor DESC;

In [0]:
%sql
SELECT brand AS Fabricante, Modelo, Valor
FROM Top_10_mostExpensive
Limit 10

In [0]:
%sql
-- 07) Crie uma coluna contendo a idade do cliente da tabela sales.customers

SELECT first_name,last_name,timestampdiff(YEAR,birth_date,NOW()) AS Idade
FROM sales.customers
WHERE timestampdiff(YEAR,birth_date,NOW()) >= 28
ORDER BY birth_date DESC;

In [0]:
%sql
-- 08) Selecionar produtos que sejam da marca HONDA, TOYOTA ou RENAULT

SELECT * FROM sales.products
WHERE brand IN
("HONDA", "TOYOTA ", "RENAULT") ;

In [0]:
%sql
-- 09) Calcule o nº de clientes da tabela customers por estado

SELECT DISTINCT state AS Estado,  count(customer_id) AS Clientes_por_Estado
FROM sales.customers
GROUP BY state
ORDER BY Clientes_por_Estado DESC

In [0]:
%sql
-- 10) Calcule o nº de clientes por estado e status profissional 

SELECT DISTINCT state AS Estado,  count(customer_id) AS Clientes_por_Estado, professional_status as Profissao
FROM sales.customers
GROUP BY ESTADO ,professional_status
ORDER BY Clientes_por_Estado DESC;

In [0]:
%sql
-- 11) Calcule o nº de clientes por estado filtrando apenas estados acima de 100 clientes

SELECT DISTINCT state AS Estado,  count(customer_id) AS Clientes_por_Estado, professional_status as Profissao
FROM sales.customers
GROUP BY ESTADO ,professional_status
ORDER BY Clientes_por_Estado DESC;